import { Badge } from '../types';

export const AVAILABLE_BADGES: Omit<Badge, 'unlockedAt' | 'progress'>[] = [
  {
    id: 'first-reflection',
    name: 'First Steps',
    description: 'Record your first reflection',
    icon: '🎬',
    requirement: 'Complete 1 reflection',
    total: 1,
  },
  {
    id: 'week-warrior',
    name: 'Week Warrior',
    description: 'Maintain a 7-day streak',
    icon: '⚡',
    requirement: 'Achieve a 7-day streak',
    total: 7,
  },
  {
    id: 'consistent-creator',
    name: 'Consistent Creator',
    description: 'Complete reflections for 5 days in a week',
    icon: '🎯',
    requirement: 'Complete 5 reflections in one week',
    total: 5,
  },
  {
    id: 'month-milestone',
    name: 'Monthly Master',
    description: 'Maintain a 30-day streak',
    icon: '🏆',
    requirement: 'Achieve a 30-day streak',
    total: 30,
  },
  {
    id: 'centurion',
    name: 'Centurion',
    description: 'Record 100 total reflections',
    icon: '💯',
    requirement: 'Complete 100 reflections',
    total: 100,
  },
  {
    id: 'early-bird',
    name: 'Early Bird',
    description: 'Complete 10 morning reflections',
    icon: '🌅',
    requirement: 'Complete 10 reflections before 9 AM',
    total: 10,
  },
  {
    id: 'night-owl',
    name: 'Night Owl',
    description: 'Complete 10 evening reflections',
    icon: '🦉',
    requirement: 'Complete 10 reflections after 8 PM',
    total: 10,
  },
  {
    id: 'gym-enthusiast',
    name: 'Gym Enthusiast',
    description: 'Record 20 gym reflections',
    icon: '💪',
    requirement: 'Complete 20 gym reflections',
    total: 20,
  },
  {
    id: 'scholar',
    name: 'Scholar',
    description: 'Record 20 class reflections',
    icon: '📚',
    requirement: 'Complete 20 class reflections',
    total: 20,
  },
  {
    id: 'comeback-kid',
    name: 'Comeback Kid',
    description: 'Start a new streak after missing days',
    icon: '🔄',
    requirement: 'Start a new 3-day streak after breaking one',
    total: 3,
  },
];

